on:
  pull_request:
    branches: [ "main" ]

jobs:
  compliance-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mkmba-nz/github-infra/actions/setup-go@HEAD

      - run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          export PATH="$HOME/go/bin:$PATH"

      - uses: pre-commit/action@v3.0.0

      # From original build job
      - run: go env

      - run: go install ./cmd/litestream

      - run: go test -v ./...

      # From original s3-mock-test job
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
#         cache: 'pip'
      - run: pip install moto[s3,server]

      - run: ./etc/s3_mock.py go test -v ./replica_client_test.go -integration s3
